[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

# API istekleri - öncelik sırası önemli
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# XML feed'i için proxy yönlendirmesi
[[redirects]]
  from = "/xml-feed"
  to = "https://stildiva.sentos.com.tr/xml-sentos-out/1"
  status = 200
  force = true

# SPA fallback - en sonda olmalı
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
