[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

# API isteklerini Netlify Function'a yönlendirir.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Diğer tüm istekleri ana sayfaya yönlendirir (SPA için).
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


# SPA (Single Page App) için catch-all kuralı
# API dışındaki tüm istekleri index.html'e yönlendirir
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# XML feed'i için proxy yönlendirmesi.
# Bu kural, /xml-feed adresine gelen istekleri alıp,
# hedef URL'den veriyi çekerek istemciye geri gönderir.
# Bu sayede tarayıcıdaki CORS hatası atlatılmış olur.
[[redirects]]
  from = "/xml-feed"
  to = "https://stildiva.sentos.com.tr/xml-sentos-out/1"
  status = 200
  force = true
