[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

# XML için proxy
[[redirects]]
  from = "/xml-feed"
  to = "https://stildiva.sentos.com.tr/xml-sentos-out/1"
  status = 200

# Shopify için proxy (API key'i URL'de)
[[redirects]]
  from = "/shopify-proxy/*"
  to = "https://verve-granul.myshopify.com/admin/api/2023-10/:splat"
  status = 200
  headers = {X-Shopify-Access-Token = "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"}

# API istekleri (basit endpoint'ler için)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# XML feed'i için proxy yönlendirmesi.
# Bu kural, /xml-feed adresine gelen istekleri alıp,
# hedef URL'den veriyi çekerek istemciye geri gönderir.
# Bu sayede tarayıcıdaki CORS hatası atlatılmış olur.
[[redirects]]
  from = "/xml-feed"
  to = "https://stildiva.sentos.com.tr/xml-sentos-out/1"
  status = 200
  force = true
